### ISSUE TITLE
Incomplete or incorrect battery stats 

### ISSUE THREAD

**Issue by RamPawar7** [Solarphlare/BatteryTile#6] opened 2023-06-27 13:43 UTC
After updating to v1.4.0, I have set up Tile text as `%t°C            %cmA • %vV`. It is displayed as following (left tile)
![20230627_184135](https://github.com/CominAtYou/BatteryTile/assets/96973076/4db22b02-a605-4f10-a399-42a45fbd89b8)
The right hand side tile is from [Battery Quick Tile](https://play.google.com/store/apps/details?id=net.xnano.android.batteryquicktile) app. The temperature on the left (this app) is incomplete. 

Also the current (both current and average) is incorrect (is always 0), and the voltage is incomplete. Following shows the stats form [Device info HW](https://play.google.com/store/apps/details?id=ru.andr7e.deviceinfohw) app from the same moment
![20230627_185430](https://github.com/CominAtYou/BatteryTile/assets/96973076/4bc67d05-3324-4350-8689-c3522c9d14e7)

I use [Charge monitor](https://play.google.com/store/apps/details?id=com.waterdaaan.chargemonitor) app to see stats chart. It shows the same stats as Device info HW app, but it says it does some sort of calibration.
![20230627_190554](https://github.com/CominAtYou/BatteryTile/assets/96973076/b58db183-f7b6-4067-8eb2-39cdd3262e8e)

Following is the log form Charge monitor app found in Settings>Calibration>Log if that helps

```
Charge Monitor 1.6.3
Brand: samsung
Model: SM-J600G
Hardware: samsungexynos7870
Android: 10

/sys/class/power_supply/ exits = true
/sys/class/power_supply/ readable = false
/sys/class/power_supply/battery exits = false
/sys/class/power_supply/battery readable = false

Jan 5 2022 20:35:56 Calibration in progress
Battery capacity start : 36%
Battery capacity now: 39%
Voltage: 3876mV
Current: 552
Jan 5 2022 21:02:12 Calibration in progress
Battery capacity start : 44%
Battery capacity now: 47%
Voltage: 3928mV
Current: 698
Jan 5 2022 21:07:18 Calibration in progress
Battery capacity start : 46%
Battery capacity now: 49%
Voltage: 3962mV
Current: 683
Jan 5 2022 21:26:40 Calibration has finished
Battery capacity: 61%
useKitKatCurrent: false
currentDivider: 1
Current is positive: true
Maximum current: 958mA
```

**Comment by RamPawar7** [comment] 2023-06-28 15:03
The current variable gives value in Amperes instead of milliamperes as mentioned in the app. So, it's incorrect and also incomplete. I found this when it showed 1 when the current was greater than 1000 milliaperes

**Comment by Solarphlare** [comment] 2023-06-30 09:53
Looking into this. Most of the issues you've reported (except the one about temperature) I can't reproduce on my own devices, so I'm trying to figure out what's causing this.

**Comment by Solarphlare** [comment] 2023-09-11 05:47
This has been resolved in [v1.5.0](https://github.com/CominAtYou/BatteryTile/releases/tag/v1.5.0)! Thanks for pointing these issues out.

**Closed as completed by Solarphlare** 2023-09-11 05:47 UTC

**Comment by RamPawar7** [comment] 2023-09-11 19:37
In the previous version, a 'space' in the text string caused the line to break. In the update, no matter how many spaces I put in, the line never breaks and all text is shown in a single line (line scrolls if the string is too long, instead of breaking at space and showing the rest on the second line as seen in [above screenshot](https://user-images.githubusercontent.com/96973076/249162637-4db22b02-a605-4f10-a399-42a45fbd89b8.jpg)). Is this intended behavior? Or should I post a new issue about this?
 
Edit: This issue stopped happening after I removed and put back the tile in the quick settings. Now the line breaks properly

**Comment by Solarphlare** [comment] 2023-09-11 20:01
As far as I know, quick settings tiles have never supported line breaks according to the Android standards. Rendering of the tile text is handled by the Android System, so it's possible that an update to a system component may have changed how the text is displayed.

**Comment by RamPawar7** [comment] 2023-09-11 20:07
Ahh okay, Thank you for the update 👍. The app works flawlessly now
